// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, U256 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
  MetadataType,
} from "dedot/contracts";

export interface ContractEvents<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractEvents<ChainApi, Type> {
  /**
   * Events emitted by the contract
   *
   *
   **/
  KillRecorded: GenericContractEvent<
    "KillRecorded",
    {
      /**
       *
       * @indexed: true
       **/
      killer: H160;
      /**
       *
       * @indexed: true
       **/
      victim: H160;
      /**
       *
       * @indexed: false
       **/
      rewardPaid: U256;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  ContractFunded: GenericContractEvent<
    "ContractFunded",
    {
      /**
       *
       * @indexed: true
       **/
      funder: H160;
      /**
       *
       * @indexed: false
       **/
      amount: U256;
    },
    Type
  >;
}
