// Generated by dedot cli

import type {
  VersionedGenericSubstrateApi,
  RpcVersion,
  RpcV2,
} from "dedot/types";
import type { InkGenericContractApi, WithLazyStorage } from "dedot/contracts";
import type { SubstrateApi } from "dedot/chaintypes";
import type { InkPrimitivesLangError, DotArena } from "./types.js";
import { ContractQuery } from "./query.js";
import { ContractTx } from "./tx.js";
import { ConstructorQuery } from "./constructor-query.js";
import { ConstructorTx } from "./constructor-tx.js";
import { ContractEvents } from "./events.js";

export * from "./types.js";

/**
 * @name: DotArenaContractApi
 * @contractName: dot_arena
 * @contractVersion: 0.1.0
 * @authors: DOT Arena Team
 * @language: ink! 6.0.0-beta.1
 **/
export interface DotArenaContractApi<
  Rv extends RpcVersion = RpcVersion,
  ChainApi extends VersionedGenericSubstrateApi = SubstrateApi,
> extends InkGenericContractApi<Rv, ChainApi> {
  metadataType: "ink";
  query: ContractQuery<ChainApi[Rv], "ink">;
  tx: ContractTx<ChainApi[Rv], "ink">;
  constructorQuery: ConstructorQuery<ChainApi[Rv], "ink">;
  constructorTx: ConstructorTx<ChainApi[Rv], DotArenaContractApi, "ink">;
  events: ContractEvents<ChainApi[Rv], "ink">;
  storage: {
    root(): Promise<DotArena>;
    lazy(): WithLazyStorage<DotArena>;
  };

  types: {
    ChainApi: ChainApi[Rv];
    RootStorage: DotArena;
    LazyStorage: WithLazyStorage<DotArena>;
    LangError: InkPrimitivesLangError;
  };
}
