// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, Result, U256 } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type { DotArenaError, InkPrimitivesLangError } from "./types.js";

export interface ContractQuery<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractQuery<ChainApi, Type> {
  /**
   * Set the game server address (only owner)
   *
   * @param {H160} server
   * @param {ContractCallOptions} options
   *
   * @selector 0xc8271125
   **/
  setGameServer: GenericContractQueryCall<
    ChainApi,
    (
      server: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], DotArenaError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Record a kill and pay reward immediately (only game server)
   * This is the ONLY function the game needs to call!
   *
   * @param {H160} killer
   * @param {H160} victim
   * @param {ContractCallOptions} options
   *
   * @selector 0x05cf2367
   **/
  recordKill: GenericContractQueryCall<
    ChainApi,
    (
      killer: H160,
      victim: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], DotArenaError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Withdraw dev fees (only owner)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x3fe15655
   **/
  withdrawDevFees: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], DotArenaError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   * Fund the contract (anyone can fund it to support prize pool)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x745fb79c
   **/
  fundContract: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], DotArenaError>,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x069db8b4
   **/
  getRewardPerKill: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<U256, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {H160} player
   * @param {ContractCallOptions} options
   *
   * @selector 0xfb61d720
   **/
  getPlayerStats: GenericContractQueryCall<
    ChainApi,
    (
      player: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        [number, U256] | undefined,
        ContractCallResult<ChainApi>
      >
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xbae47bb0
   **/
  getDevBalance: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<U256, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xbe15a422
   **/
  getContractBalance: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<U256, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x5317c87d
   **/
  getGameServer: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult<ChainApi>>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x07fcd0b1
   **/
  getOwner: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<H160, ContractCallResult<ChainApi>>>,
    Type
  >;
}
