// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160 } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  ChainApi extends GenericSubstrateApi,
  Type extends MetadataType,
> extends GenericContractTx<ChainApi, Type> {
  /**
   * Set the game server address (only owner)
   *
   * @param {H160} server
   * @param {ContractTxOptions} options
   *
   * @selector 0xc8271125
   **/
  setGameServer: GenericContractTxCall<
    ChainApi,
    (
      server: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Record a kill and pay reward immediately (only game server)
   * This is the ONLY function the game needs to call!
   *
   * @param {H160} killer
   * @param {H160} victim
   * @param {ContractTxOptions} options
   *
   * @selector 0x05cf2367
   **/
  recordKill: GenericContractTxCall<
    ChainApi,
    (
      killer: H160,
      victim: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Withdraw dev fees (only owner)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x3fe15655
   **/
  withdrawDevFees: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Fund the contract (anyone can fund it to support prize pool)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x745fb79c
   **/
  fundContract: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
