// Generated by dedot cli

import type { U256, H160 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type DotArenaPlayerStats = { totalKills: number; totalEarned: U256 };

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type DotArena = {
  rewardPerKill: U256;
  devFeePercent: number;
  devBalance: U256;
  playerStats: { get(arg: H160): Promise<DotArenaPlayerStats | undefined> };
  owner: H160;
  gameServer?: H160 | undefined;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type DotArenaError =
  | "Unauthorized"
  | "TransferFailed"
  | "InsufficientBalance";
